name: Backlinks Checker

on:
  schedule:
    - cron: '0 */6 * * *'  # Roda a cada 6 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  check-backlinks:
    runs-on: ubuntu-22.04
    timeout-minutes: 30  # Define um timeout de 30 minutos
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'  # Habilita cache do pip
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgbm1
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        pip install gdown
        pip install google-auth-oauthlib
        pip install google-auth-httplib2
        pip install google-api-python-client
    
    - name: Install Playwright browsers
      run: |
        python -m playwright install chromium
        python -m playwright install-deps
    
    - name: Create domains.txt if not exists
      run: |
        if [ ! -f domains.txt ]; then
          echo "example.com" > domains.txt
        fi
    
    - name: Create Google Drive directory
      run: mkdir -p "Google Drive"
    
    - name: Create config.py
      run: |
        cat > config.py << EOL
        # Credenciais do SEOPack
        SEOPACK_LOGIN = "${{ secrets.SEOPACK_LOGIN }}"
        SEOPACK_PASSWORD = "${{ secrets.SEOPACK_PASSWORD }}"
        
        # URLs
        SEOPACK_LOGIN_URL = "https://seopacktools.com/login"
        SEOPACK_DASHBOARD_URL = "https://smr.seopacktools.com/dashboard"
        EOL
    
    - name: Run backlinks checker
      env:
        DISPLAY: :99
        PLAYWRIGHT_BROWSERS_PATH: /home/runner/.cache/ms-playwright
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python domain_checker.py || {
          echo "Script failed with exit code $?"
          exit 1
        }
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: backlinks-results
        path: |
          Google Drive/
          debug/
        retention-days: 7 