name: Backlinks Checker

on:
  schedule:
    - cron: '0 */6 * * *'  # Roda a cada 6 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  check-backlinks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium
    
    - name: Create domains.txt if not exists
      run: |
        if [ ! -f domains.txt ]; then
          echo "example.com" > domains.txt
        fi
    
    - name: Run backlinks checker
      env:
        SEOPACK_LOGIN: ${{ secrets.SEOPACK_LOGIN }}
        SEOPACK_PASSWORD: ${{ secrets.SEOPACK_PASSWORD }}
      run: python domain_checker.py
    
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: backlinks-results
        path: |
          Google Drive/
          debug/ 